### ISSUE TITLE
rudeck

### ISSUE THREAD

**Issue by shinji19** [shinji19/til#91]
job scheduler
https://dev.classmethod.jp/server-side/server/try-rundeck-job/

**Comment by shinji19** [comment]
```
version: '2'

services:
  rundeck:
    image: jordan/rundeck:latest
    environment:
      SERVER_URL: http://localhost:4440
#    volumes:
#      - ./etc/rundeck:/etc/rundeck
#      - ./opt/rundeck-plugins:/opt/rundeck-plugins
#      - ./var/lib/mysql:/var/lib/mysql
#      - ./var/lib/rundeck:/var/lib/rundeck
#      - ./var/lib/rundeck/logs:/var/lib/rundeck/logs
#      - ./var/lib/rundeck/var/storage:/var/lib/rundeck/var/storage
#      - ./var/log/rundeck:/var/log/rundeck
#      - ./var/rundeck:/var/rundeck
    ports:
      - 4440:4440
```
